---
env:
  es2020: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  indent: off
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-sparse-arrays: error
  no-unused-vars:
    - error
    - varsIgnorePattern: "^[A-Z]"
      argsIgnorePattern: ".*"
  "@typescript-eslint/no-non-null-assertion":
    - warn
  "@typescript-eslint/no-empty-interface":
    - off